apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-web
  namespace: cloud-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-StatefulSet
  serviceName: nginx-web
  template:
    metadata:
      labels:
        app: nginx-StatefulSet
    spec:
      containers:
        - name: nginx
          image: nginx:1.21.6
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-volume
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: nginx-volume
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: rook-ceph-block
        resources:
          requests:
            storage: 2Gi