kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx-rbd-pvc
  namespace: cloud-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-ceph-block